name: my_genderizeio
description: Öğrenmek için oluşturduğum dart paketi
version: 1.0.0
repository: https://github.com/berkayismus/genderizeio

environment:
  sdk: '>=2.19.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dependencies: 
  http: ^0.13.5

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.21.0
